default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: veritas
  username: postgres
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: localhost
  port: 5432

test:
  <<: *default
  database: veritas_test

production:
  primary: &primary_production
    <<: *default
    database: DATABASE_VERITAS
    username: postgres
    password: <%= ENV["DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: veritas_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: veritas_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: veritas_production_cable
    migrations_paths: db/cable_migrate
